### ISSUE TITLE
Add Delta Chat to the list of production users

### ISSUE THREAD

**Issue by link2xt** [rust-lang/www.rust-lang.org#1810]
I would like to add [Delta Chat](https://delta.chat/) to the [list of production users of Rust](https://www.rust-lang.org/production/users). Delta Chat has been successfully using Rust to develop [cross-platform core library](https://github.com/deltachat/deltachat-core-rust/) of the messenger used on Android, iOS, Windows, macOS and Linux.

The description for https://github.com/rust-lang/www.rust-lang.org/blob/master/src/data/users.yml may look like this:
```yaml
-
  name: Delta Chat
  url: https://delta.chat/
  logo: deltachat.svg
  how: "Delta Chat uses the <a href='https://github.com/deltachat/deltachat-core-rust'>core library</a> written in Rust to handle [email protocols](https://github.com/async-email) and [OpenPGP encryption](https://github.com/rpgp/rpgp) uniformly across Android, iOS, Windows, macOS and Linux."
```

SVG logo is available on the Delta Chat website: https://delta.chat/assets/logos/delta-chat.svg
